/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedRegisterRouteImport } from './routes/_authenticated/register'
import { Route as AuthenticatedArtistsIndexRouteImport } from './routes/_authenticated/artists.index'
import { Route as AuthenticatedArtistsArtistIdRouteImport } from './routes/_authenticated/artists.$artistId'
import { Route as AuthenticatedNotesNewRouteImport } from './routes/_authenticated/notes.new'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as AuthenticatedNotesNoteIdEditRouteImport } from './routes/_authenticated/notes.$noteId.edit'
import { Route as ApiPublicMcpKeyRouteImport } from './routes/api/public/mcp.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegisterRoute = AuthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArtistsIndexRoute =
  AuthenticatedArtistsIndexRouteImport.update({
    id: '/artists/',
    path: '/artists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArtistsArtistIdRoute =
  AuthenticatedArtistsArtistIdRouteImport.update({
    id: '/artists/$artistId',
    path: '/artists/$artistId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotesNewRoute = AuthenticatedNotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotesNoteIdEditRoute =
  AuthenticatedNotesNoteIdEditRouteImport.update({
    id: '/notes/$noteId/edit',
    path: '/notes/$noteId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMcpKeyRoute = ApiPublicMcpKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiPublicMcpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/artists/$artistId': typeof AuthenticatedArtistsArtistIdRoute
  '/notes/new': typeof AuthenticatedNotesNewRoute
  '/api/public/mcp': typeof ApiPublicMcpRouteWithChildren
  '/artists/': typeof AuthenticatedArtistsIndexRoute
  '/notes/$noteId/edit': typeof AuthenticatedNotesNoteIdEditRoute
  '/api/public/mcp/$key': typeof ApiPublicMcpKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/artists/$artistId': typeof AuthenticatedArtistsArtistIdRoute
  '/notes/new': typeof AuthenticatedNotesNewRoute
  '/api/public/mcp': typeof ApiPublicMcpRouteWithChildren
  '/artists': typeof AuthenticatedArtistsIndexRoute
  '/notes/$noteId/edit': typeof AuthenticatedNotesNoteIdEditRoute
  '/api/public/mcp/$key': typeof ApiPublicMcpKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/register': typeof AuthenticatedRegisterRoute
  '/_authenticated/artists/$artistId': typeof AuthenticatedArtistsArtistIdRoute
  '/_authenticated/notes/new': typeof AuthenticatedNotesNewRoute
  '/api/public/mcp': typeof ApiPublicMcpRouteWithChildren
  '/_authenticated/artists/': typeof AuthenticatedArtistsIndexRoute
  '/_authenticated/notes/$noteId/edit': typeof AuthenticatedNotesNoteIdEditRoute
  '/api/public/mcp/$key': typeof ApiPublicMcpKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/artists/$artistId'
    | '/notes/new'
    | '/api/public/mcp'
    | '/artists/'
    | '/notes/$noteId/edit'
    | '/api/public/mcp/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/artists/$artistId'
    | '/notes/new'
    | '/api/public/mcp'
    | '/artists'
    | '/notes/$noteId/edit'
    | '/api/public/mcp/$key'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/register'
    | '/_authenticated/artists/$artistId'
    | '/_authenticated/notes/new'
    | '/api/public/mcp'
    | '/_authenticated/artists/'
    | '/_authenticated/notes/$noteId/edit'
    | '/api/public/mcp/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiPublicMcpRoute: typeof ApiPublicMcpRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/register': {
      id: '/_authenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artists/': {
      id: '/_authenticated/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof AuthenticatedArtistsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artists/$artistId': {
      id: '/_authenticated/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof AuthenticatedArtistsArtistIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes/new': {
      id: '/_authenticated/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AuthenticatedNotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notes/$noteId/edit': {
      id: '/_authenticated/notes/$noteId/edit'
      path: '/notes/$noteId/edit'
      fullPath: '/notes/$noteId/edit'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mcp/$key': {
      id: '/api/public/mcp/$key'
      path: '/$key'
      fullPath: '/api/public/mcp/$key'
      preLoaderRoute: typeof ApiPublicMcpKeyRouteImport
      parentRoute: typeof ApiPublicMcpRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRegisterRoute: typeof AuthenticatedRegisterRoute
  AuthenticatedArtistsArtistIdRoute: typeof AuthenticatedArtistsArtistIdRoute
  AuthenticatedNotesNewRoute: typeof AuthenticatedNotesNewRoute
  AuthenticatedArtistsIndexRoute: typeof AuthenticatedArtistsIndexRoute
  AuthenticatedNotesNoteIdEditRoute: typeof AuthenticatedNotesNoteIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRegisterRoute: AuthenticatedRegisterRoute,
  AuthenticatedArtistsArtistIdRoute: AuthenticatedArtistsArtistIdRoute,
  AuthenticatedNotesNewRoute: AuthenticatedNotesNewRoute,
  AuthenticatedArtistsIndexRoute: AuthenticatedArtistsIndexRoute,
  AuthenticatedNotesNoteIdEditRoute: AuthenticatedNotesNoteIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicMcpRouteChildren {
  ApiPublicMcpKeyRoute: typeof ApiPublicMcpKeyRoute
}

const ApiPublicMcpRouteChildren: ApiPublicMcpRouteChildren = {
  ApiPublicMcpKeyRoute: ApiPublicMcpKeyRoute,
}

const ApiPublicMcpRouteWithChildren = ApiPublicMcpRoute._addFileChildren(
  ApiPublicMcpRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiPublicMcpRoute: ApiPublicMcpRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
